const data = [
  {
    title: "pic1",
    src: "./dist/images/1.jpg",
    src2: "./dist/images/2.jpg",
    src3: "./dist/images/3.jpg",
    src4: "./dist/images/4.jpg",
    price: "999",
    featured: false,
    id: 1,
  },
  {
    title: "pic2",
    src: "./dist/images/2.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: true,
    id: 2,
  },
  {
    title: "pic3",
    src: "./dist/images/3.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: true,
    id: 3,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: true,
    id: 4,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: false,
    id: 5,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: false,
    id: 6,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: false,
    id: 7,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: false,
    id: 8,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: false,
    id: 9,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: false,
    id: 10,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: false,
    id: 11,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: false,
    id: 12,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: false,
    id: 13,
  },
  {
    title: "pic4",
    src: "./dist/images/4.jpg",
    src2: "./dist/images/2.jpg",
    price: "999",
    featured: false,
    id: 14,
  },
];

export default data;
